#ifndef __FUNCTION_MANAGER__HH__
#define __FUNCTION_MANAGER__HH__

#include <iostream>
#include <string>
#include <functional>

/**
 * \brief Class for selecting mathematical functions to generate matrix elements.
 *
 * This class allows the selection of predefined functions (such as "identity" or "hilbert")
 * based on the input function name. Once selected, these functions can be used to generate
 * matrix elements at specified row and column positions.
 *
 * \tparam T The data type of the matrix elements (e.g. float, double).
 */
template <typename T>
class FunctionManager
{
public:
    /// Constructor
    FunctionManager(const std::string &functionName);
    /// Destructor
    ~FunctionManager();
    /**
     * \brief Operator() that generates the matrix element for a given row and column.
     *
     * Calls the selected function to generate the matrix element for the specified row and column.
     *
     * \param row The row index of the matrix element.
     * \param col The column index of the matrix element.
     * \return The matrix element generated by the selected function.
     */
    T operator()(int row, int col);

private:
    std::function<T(int, int)> selectedFunction; /**< Holds the selected function. */
    /**
     * \brief Generates an identity matrix element.
     *
     * This function generates an element for the identity matrix. The element at position \f$(i, j)\f$ is:
     * \f[a_{i,j} = \begin{cases} 1 & \text{if } i = j \\
     *                            0 & \text{otherwise} \end{cases} \f]
     * where \f$i\f$ and \f$j\f$ are 1-indexed row and column indices.
     *
     * \param row The row index of the matrix element (\f$i\f$).
     * \param col The column index of the matrix element (\f$j\f$).
     * \return The identity matrix element.
     */
    T IdentityMatrix(int row, int col);
    /**
     * \brief Generates a Hilbert matrix element.
     *
     * This function generates an element for a Hilbert matrix. The element at position \f$(i, j)\f$ is:
     * \f[ a_{i,j} = \frac{1}{i + j - 1} \f]
     * where \f$i\f$ and \f$j\f$ are 1-indexed row and column indices.
     *
     * \param row The row index of the matrix element (\f$i\f$).
     * \param col The column index of the matrix element (\f$j\f$).
     * \return The Hilbert matrix element.
     */
    T HilbertMatrix(int row, int col);
};

#endif